name: Android Release

on:
  push:
    branches:
      - master

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - name: Generate version
        id: version
        run: |
          VERSION=$(date +'%Y%m%d').${{ github.run_number }}
          echo "version=$VERSION" >> $GITHUB_OUTPUT
          echo "Generated version: $VERSION"

      - uses: actions/checkout@v4
      
      - name: Setup Flutter
        uses: subosito/flutter-action@v2
        with:
          flutter-version: '3.19.0'
          channel: 'stable'
          
      - name: Install dependencies
        run: flutter pub get
        
      - name: Build Android App Bundle
        run: flutter build appbundle
        
      - name: Publish to GitHub Packages
        uses: actions/upload-artifact@v4
        with:
          name: app-${{ steps.version.outputs.version }}.aab
          path: build/app/outputs/bundle/release/app-release.aab
